### ISSUE TITLE
轨迹厨狂喜。非常感谢贡献！

### ISSUE THREAD

**Issue by YoungHector** [trails-game/trails-script-mkdocs#39]
辛苦了！

**Comment by Llugaes** [comment]
辛苦！

**Comment by Azimiao** [comment]
我也非常感谢编辑团队成员的辛苦付出。不过由于 Issues 主要用来报告问题，所以先关掉了，哈哈~

欢迎各位参与编辑、校对工作，或者加入 QQ 群来聊天~（901434394）
